window.REYKJAVIK_SOURCES = [
  {
    id: "frus-v-ch6",
    title: "FRUS 1981-1988, Volume V, chapter 6: Daniloff, SDI, and the Reykjavik Summit",
    date: "1986-08-30",
    phase: "Road",
    side: "US",
    priority: "Context",
    type: "collection",
    repository: "Office of the Historian",
    collection: "FRUS 1981-1988, Volume V",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v05/ch6",
    summary: "Official U.S. documentary chapter covering the September-October 1986 run-up, the summit sessions, and immediate post-summit accounts."
  },
  {
    id: "frus-v-d280",
    title: "Gorbachev letter to Reagan proposing a quick meeting in Iceland or London",
    date: "1986-09-15",
    phase: "Road",
    side: "Soviet",
    priority: "Core",
    type: "letter",
    repository: "Office of the Historian",
    collection: "FRUS V, Document 280",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v05/d280",
    summary: "The September 15 message that set the Reykjavik meeting in motion and framed the Soviet desire to break the post-Geneva deadlock."
  },
  {
    id: "frus-v-d293",
    title: "Shultz memorandum to Reagan on Reykjavik",
    date: "1986-10-02",
    phase: "Road",
    side: "US",
    priority: "Context",
    type: "memorandum",
    repository: "Office of the Historian",
    collection: "FRUS V, Document 293",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v05/d293",
    summary: "Secretary Shultz briefs Reagan on objectives and expectations before Iceland."
  },
  {
    id: "frus-v-d294",
    title: "Poindexter memorandum to Reagan on small confidential meetings",
    date: "1986-10-03",
    phase: "Road",
    side: "US",
    priority: "Context",
    type: "memorandum",
    repository: "Office of the Historian",
    collection: "FRUS V, Document 294",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v05/d294",
    summary: "NSC guidance on why small direct sessions with Soviet interlocutors could be tactically useful."
  },
  {
    id: "frus-v-d295",
    title: "Jack Matlock paper on Soviet negotiating psychology",
    date: "1986-10-04",
    phase: "Road",
    side: "US",
    priority: "Context",
    type: "paper",
    repository: "Office of the Historian",
    collection: "FRUS V, Document 295",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v05/d295",
    summary: "A pre-summit NSC paper using the Daniloff affair to advise Reagan on Soviet tactics and psychology."
  },
  {
    id: "frus-v-d296",
    title: "Senior Arms Control Group issue paper before Reykjavik",
    date: "1986-10-06",
    phase: "Road",
    side: "US",
    priority: "Context",
    type: "policy paper",
    repository: "Office of the Historian",
    collection: "FRUS V, Document 296",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v05/d296",
    summary: "Repackaged Defense and Space and INF options prepared for senior arms-control deliberations just before the meeting."
  },
  {
    id: "frus-v-d297",
    title: "NSC talking points for Poindexter at the October 7 NSPG meeting",
    date: "1986-10-07",
    phase: "Road",
    side: "US",
    priority: "Context",
    type: "talking points",
    repository: "Office of the Historian",
    collection: "FRUS V, Document 297",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v05/d297",
    summary: "Talking points for the final high-level policy discussion before Reagan left for Iceland."
  },
  {
    id: "frus-v-d298",
    title: "National Security Decision Directive 245: Reagan-Gorbachev preparatory meeting",
    date: "1986-10-07",
    phase: "Road",
    side: "US",
    priority: "Context",
    type: "directive",
    repository: "Office of the Historian",
    collection: "FRUS V, Document 298",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v05/d298",
    summary: "Formal White House guidance for the Reykjavik preparatory meeting."
  },
  {
    id: "frus-v-d299",
    title: "Weinberger letter to Reagan on security and arms reductions",
    date: "1986-10-09",
    phase: "Road",
    side: "US",
    priority: "Context",
    type: "letter",
    repository: "Office of the Historian",
    collection: "FRUS V, Document 299",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v05/d299",
    summary: "Defense Secretary Weinberger's eve-of-summit advice to preserve SDI and handle arms reductions with caution."
  },
  {
    id: "frus-v-d300",
    title: "Editorial note on Reagan's departure remarks",
    date: "1986-10-09",
    phase: "Public",
    side: "US",
    priority: "Context",
    type: "public remarks",
    repository: "Office of the Historian",
    collection: "FRUS V, Document 300",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v05/d300",
    summary: "FRUS note summarizing Reagan's October 9 statement before leaving Washington for Iceland."
  },
  {
    id: "frus-v-d301",
    title: "First Reagan-Gorbachev meeting at Hofdi House",
    date: "1986-10-11",
    phase: "Summit",
    side: "US",
    priority: "Core",
    type: "memorandum of conversation",
    repository: "Office of the Historian",
    collection: "FRUS V, Document 301",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v05/d301",
    summary: "U.S. record of the first leader session, 10:40 a.m.-12:30 p.m., including the opening agenda and Gorbachev's proposals."
  },
  {
    id: "frus-v-d302",
    title: "Second Reagan-Gorbachev meeting at Hofdi House",
    date: "1986-10-11",
    phase: "Summit",
    side: "US",
    priority: "Core",
    type: "memorandum of conversation",
    repository: "Office of the Historian",
    collection: "FRUS V, Document 302",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v05/d302",
    summary: "U.S. record of the October 11 afternoon session, 3:30-5:40 p.m., centered on START, INF, SDI, and testing."
  },
  {
    id: "frus-v-d303",
    title: "Overnight non-arms-control working group record",
    date: "1986-10-11",
    phase: "Summit",
    side: "Bilateral",
    priority: "Core",
    type: "draft memorandum of conversation",
    repository: "Office of the Historian",
    collection: "FRUS V, Document 303",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v05/d303",
    summary: "Draft record of the October 11-12 working-group session on regional and bilateral issues."
  },
  {
    id: "frus-v-d305",
    title: "Report to the President on the overnight negotiating teams",
    date: "1986-10-12",
    phase: "Summit",
    side: "US",
    priority: "Core",
    type: "briefing paper",
    repository: "Office of the Historian",
    collection: "FRUS V, Document 305",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v05/d305",
    summary: "A morning report summarizing the overnight U.S.-Soviet arms-control work led by Nitze and Akhromeyev."
  },
  {
    id: "frus-v-d306",
    title: "Third Reagan-Gorbachev meeting at Hofdi House",
    date: "1986-10-12",
    phase: "Summit",
    side: "US",
    priority: "Core",
    type: "memorandum of conversation",
    repository: "Office of the Historian",
    collection: "FRUS V, Document 306",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v05/d306",
    summary: "U.S. record of the Sunday morning leader session, 10 a.m.-1:35 p.m., reviewing overnight results and the SDI/ABM dispute."
  },
  {
    id: "frus-v-d307",
    title: "Shultz-Shevardnadze drafting meeting",
    date: "1986-10-12",
    phase: "Summit",
    side: "Bilateral",
    priority: "Core",
    type: "memorandum of conversation",
    repository: "Office of the Historian",
    collection: "FRUS V, Document 307",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v05/d307",
    summary: "Record of the urgent 2:05-3 p.m. ministerial session on ABM Treaty non-withdrawal and SDI language."
  },
  {
    id: "frus-v-d308",
    title: "Final Reagan-Gorbachev meeting at Hofdi House",
    date: "1986-10-12",
    phase: "Summit",
    side: "US",
    priority: "Core",
    type: "memorandum of conversation",
    repository: "Office of the Historian",
    collection: "FRUS V, Document 308",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v05/d308",
    summary: "U.S. record of the decisive final session, 3:25-4:30 p.m. and 5:30-6:50 p.m., where the near-agreement broke over SDI constraints."
  },
  {
    id: "frus-v-d309",
    title: "Editorial note on the end of Reykjavik",
    date: "1986-10-12",
    phase: "Aftermath",
    side: "Bilateral",
    priority: "Core",
    type: "editorial note",
    repository: "Office of the Historian",
    collection: "FRUS V, Document 309",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v05/d309",
    summary: "FRUS note linking Reagan's diary, Gorbachev's memoir, and Palazhchenko's account of the unhappy departure."
  },
  {
    id: "frus-xi-ch3",
    title: "FRUS 1981-1988, Volume XI, START I, chapter 3",
    date: "1986-10-11",
    phase: "Summit",
    side: "US",
    priority: "Context",
    type: "collection",
    repository: "Office of the Historian",
    collection: "FRUS 1981-1988, Volume XI",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v11/ch3",
    summary: "Official START I volume chapter containing the arms-control records around Reykjavik and the follow-up negotiating guidance."
  },
  {
    id: "frus-xi-d159",
    title: "Overnight arms-control experts meeting, Nitze-Akhromeyev group",
    date: "1986-10-11",
    phase: "Summit",
    side: "Bilateral",
    priority: "Core",
    type: "memorandum of conversation",
    repository: "Office of the Historian",
    collection: "FRUS XI, Document 159",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v11/d159",
    summary: "START volume record of the 8 p.m.-6:30 a.m. arms-control working-group meeting at Hofdi House."
  },
  {
    id: "frus-xi-d160",
    title: "Charles Hill notes from the early-morning Reykjavik arms-control talks",
    date: "1986-10-12",
    phase: "Summit",
    side: "US",
    priority: "Core",
    type: "notes",
    repository: "Office of the Historian",
    collection: "FRUS XI, Document 160",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v11/d160",
    summary: "Hill's notes from the overnight negotiations, with appendix image in the START volume."
  },
  {
    id: "frus-xi-d161",
    title: "Charles Hill notes before the Sunday morning leader session",
    date: "1986-10-12",
    phase: "Summit",
    side: "US",
    priority: "Core",
    type: "notes",
    repository: "Office of the Historian",
    collection: "FRUS XI, Document 161",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v11/d161",
    summary: "Hill's 7:10 a.m. notes on the state of the arms-control package before the leaders reconvened."
  },
  {
    id: "frus-xi-d162",
    title: "START-volume extract of the Sunday morning leader meeting",
    date: "1986-10-12",
    phase: "Summit",
    side: "US",
    priority: "Core",
    type: "memorandum of conversation",
    repository: "Office of the Historian",
    collection: "FRUS XI, Document 162",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v11/d162",
    summary: "START-specific presentation of the October 12 morning Reagan-Gorbachev session."
  },
  {
    id: "frus-xi-d163",
    title: "START-volume record of the Shultz-Shevardnadze session",
    date: "1986-10-12",
    phase: "Summit",
    side: "Bilateral",
    priority: "Core",
    type: "memorandum of conversation",
    repository: "Office of the Historian",
    collection: "FRUS XI, Document 163",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v11/d163",
    summary: "Arms-control volume version of the last-minute ministerial discussion."
  },
  {
    id: "frus-xi-d164",
    title: "START-volume record of the final Reagan-Gorbachev session",
    date: "1986-10-12",
    phase: "Summit",
    side: "US",
    priority: "Core",
    type: "memorandum of conversation",
    repository: "Office of the Historian",
    collection: "FRUS XI, Document 164",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v11/d164",
    summary: "START-focused version of the final session and collapse over SDI/ABM language."
  },
  {
    id: "frus-xi-d166",
    title: "Rowny memorandum on Reykjavik negotiations",
    date: "1986-10-22",
    phase: "Aftermath",
    side: "US",
    priority: "Context",
    type: "memorandum of conversation",
    repository: "Office of the Historian",
    collection: "FRUS XI, Document 166",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v11/d166",
    summary: "Post-summit arms-control record drafted by Edward Rowny."
  },
  {
    id: "frus-xi-d169",
    title: "National Security Decision Directive 249",
    date: "1986-10-29",
    phase: "Aftermath",
    side: "US",
    priority: "Context",
    type: "directive",
    repository: "Office of the Historian",
    collection: "FRUS XI, Document 169",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v11/d169",
    summary: "Supplemental guidance for the Nuclear and Space Talks after Reykjavik."
  },
  {
    id: "frus-vi-d1",
    title: "Iceland Chronology",
    date: "1986-10-18",
    phase: "Aftermath",
    side: "US",
    priority: "Core",
    type: "chronology",
    repository: "Office of the Historian",
    collection: "FRUS VI, Document 1",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v06/d1",
    summary: "Detailed U.S. government chronology of the Reykjavik trip, explicitly framed as a chronology rather than a negotiating record."
  },
  {
    id: "frus-vi-d3",
    title: "NSPG meeting on arms-control follow-up to Reykjavik",
    date: "1986-10-27",
    phase: "Aftermath",
    side: "US",
    priority: "Context",
    type: "minutes",
    repository: "Office of the Historian",
    collection: "FRUS VI, Document 3",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v06/d3",
    summary: "Minutes of Reagan's National Security Planning Group discussion on allied reactions and post-Reykjavik arms-control strategy."
  },
  {
    id: "frus-vi-d4",
    title: "Hartman telegram on preparing for Shultz-Shevardnadze talks",
    date: "1986-10-31",
    phase: "Aftermath",
    side: "US",
    priority: "Context",
    type: "telegram",
    repository: "Office of the Historian",
    collection: "FRUS VI, Document 4",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v06/d4",
    summary: "Ambassador Hartman argues the Reykjavik deal was still alive and that Vienna talks could get the process back on track."
  },
  {
    id: "frus-vi-d6",
    title: "Shultz-Shevardnadze meeting in Vienna",
    date: "1986-11-05",
    phase: "Aftermath",
    side: "Bilateral",
    priority: "Context",
    type: "memorandum of conversation",
    repository: "Office of the Historian",
    collection: "FRUS VI, Document 6",
    url: "https://history.state.gov/historicaldocuments/frus1981-88v06/d6",
    summary: "Follow-up ministerial discussion on the Reykjavik issues during the Vienna CSCE review meeting."
  },
  {
    id: "nsa-ebb203",
    title: "The Reykjavik File: previously secret U.S. and Soviet documents",
    date: "2006-10-13",
    phase: "Collections",
    side: "Bilateral",
    priority: "Core",
    type: "document collection",
    repository: "National Security Archive",
    collection: "Electronic Briefing Book No. 203",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/index.htm",
    summary: "Compact public side-by-side collection. Individual U.S. documents reproduced in FRUS are represented in this workbench by their history.state.gov records."
  },
  {
    id: "nsa203-doc02",
    title: "Politburo discussion of Reagan's response and strategic disarmament",
    date: "1986-09-22",
    phase: "Road",
    side: "Soviet",
    priority: "Core",
    type: "Politburo record",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 2",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document02.pdf",
    summary: "Soviet leadership discussion after Shevardnadze reported from Washington and Reagan accepted the Iceland meeting."
  },
  {
    id: "nsa203-doc03",
    title: "Gorbachev discussion with assistants on Reykjavik preparations",
    date: "1986-09-29",
    phase: "Road",
    side: "Soviet",
    priority: "Core",
    type: "meeting notes",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 3",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document03.pdf",
    summary: "Gorbachev stresses the active, initiative-driven Soviet position being prepared for Reykjavik."
  },
  {
    id: "nsa203-doc05",
    title: "Gorbachev instructions for the Reykjavik preparation group",
    date: "1986-10-04",
    phase: "Road",
    side: "Soviet",
    priority: "Core",
    type: "instructions",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 5",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document05.pdf",
    summary: "Gorbachev sets priorities and asks for a position with breakthrough potential, tied to nuclear abolition."
  },
  {
    id: "nsa203-doc06",
    title: "Sestanovich memorandum: Gorbachev's goals and tactics at Reykjavik",
    date: "1986-10-04",
    phase: "Road",
    side: "US",
    priority: "Context",
    type: "intelligence assessment",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 6",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document06.pdf",
    summary: "NSC assessment that misread the scale of Gorbachev's intended concessions."
  },
  {
    id: "nsa203-doc07",
    title: "State Department issues checklist and walk-through for Shultz",
    date: "1986-10-07",
    phase: "Road",
    side: "US",
    priority: "Context",
    type: "briefing book",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 7",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document07.pdf",
    summary: "Selected sections from Shultz's summit briefing book: checklist and agenda walk-through."
  },
  {
    id: "nsa203-doc08",
    title: "Politburo session on final preparations for Reykjavik",
    date: "1986-10-08",
    phase: "Road",
    side: "Soviet",
    priority: "Core",
    type: "Politburo record",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 8",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document08.pdf",
    summary: "Final Soviet leadership review before departure, including proposals on INF, ABM, and strategic arms."
  },
  {
    id: "nsa203-doc10",
    title: "Russian transcript: Reykjavik morning session, October 11",
    date: "1986-10-11",
    phase: "Summit",
    side: "Soviet",
    priority: "Core",
    type: "meeting transcript",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 10",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document10.pdf",
    summary: "FBIS translation of the Russian transcript for the first leader session."
  },
  {
    id: "nsa203-doc12",
    title: "Russian transcript: Reykjavik afternoon session, October 11",
    date: "1986-10-11",
    phase: "Summit",
    side: "Soviet",
    priority: "Core",
    type: "meeting transcript",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 12",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document12.pdf",
    summary: "FBIS translation of the Russian transcript for the second leader session."
  },
  {
    id: "nsa203-doc14",
    title: "Russian transcript: Reykjavik morning session, October 12",
    date: "1986-10-12",
    phase: "Summit",
    side: "Soviet",
    priority: "Core",
    type: "meeting transcript",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 14",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document14.pdf",
    summary: "FBIS translation of the Russian transcript for the third leader session."
  },
  {
    id: "nsa203-doc16",
    title: "Russian transcript: Reykjavik afternoon session, October 12",
    date: "1986-10-12",
    phase: "Summit",
    side: "Soviet",
    priority: "Core",
    type: "meeting transcript",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 16",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document16.pdf",
    summary: "FBIS translation of the Russian transcript for the final leader session."
  },
  {
    id: "nsa203-doc17",
    title: "Russian transcript of the military working group",
    date: "1986-10-11",
    phase: "Summit",
    side: "Soviet",
    priority: "Core",
    type: "working-group transcript",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 17",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document17.pdf",
    summary: "Fifty-two-page Russian record of the all-night Nitze-Akhromeyev military issues negotiations."
  },
  {
    id: "nsa203-doc18",
    title: "Lessons of Reykjavik",
    date: "1986-10-12",
    phase: "Aftermath",
    side: "US",
    priority: "Context",
    type: "summary paper",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 18",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document18.pdf",
    summary: "A short State Department post-summit paper, likely written on the last day of the summit."
  },
  {
    id: "nsa203-doc19",
    title: "Gorbachev reflections on Reykjavik on the flight to Moscow",
    date: "1986-10-12",
    phase: "Aftermath",
    side: "Soviet",
    priority: "Core",
    type: "reflections",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 19",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document19.pdf",
    summary: "Chernyaev's notes of Gorbachev's positive assessment while returning from Iceland."
  },
  {
    id: "nsa203-doc21",
    title: "Politburo session on results of the Reykjavik Summit",
    date: "1986-10-14",
    phase: "Aftermath",
    side: "Soviet",
    priority: "Core",
    type: "Politburo record",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 21",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document21.pdf",
    summary: "First post-summit Politburo discussion, with Gorbachev presenting Reykjavik as a breakthrough despite the stalemate."
  },
  {
    id: "nsa203-doc22",
    title: "Politburo session on expulsions and U.S. retreat from Reykjavik",
    date: "1986-10-22",
    phase: "Aftermath",
    side: "Soviet",
    priority: "Context",
    type: "Politburo record",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 22",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document22.pdf",
    summary: "Soviet leadership discussion linking the diplomatic expulsions to the effort to hold Reagan to the Reykjavik agenda."
  },
  {
    id: "nsa203-doc23",
    title: "Politburo assessment and Geneva instructions after Reykjavik",
    date: "1986-10-30",
    phase: "Aftermath",
    side: "Soviet",
    priority: "Core",
    type: "Politburo record",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 23",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document23.pdf",
    summary: "Gorbachev and Shevardnadze debate how to reveal a new Soviet position on SDI testing and preserve the Reykjavik agenda."
  },
  {
    id: "nsa203-doc24",
    title: "Poindexter memorandum on post-Reykjavik follow-up",
    date: "1986-11-01",
    phase: "Aftermath",
    side: "US",
    priority: "Context",
    type: "memorandum",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 24",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document24.pdf",
    summary: "Cover memo on developing the administration's post-Reykjavik follow-up directive."
  },
  {
    id: "nsa203-doc25",
    title: "NSDD 250: Post-Reykjavik Follow-Up",
    date: "1986-11-03",
    phase: "Aftermath",
    side: "US",
    priority: "Core",
    type: "directive",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 25",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document25.pdf",
    summary: "Reagan-signed directive trying to keep the bureaucracy focused on eliminating ballistic missiles after Reykjavik."
  },
  {
    id: "nsa203-doc26",
    title: "Politburo discussion of Shevardnadze-Shultz Vienna talks",
    date: "1986-11-13",
    phase: "Aftermath",
    side: "Soviet",
    priority: "Context",
    type: "Politburo record",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 26",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document26.pdf",
    summary: "Soviet leadership reaction to the Vienna follow-up, including Gorbachev's insistence that Reykjavik had changed the level of disarmament dialogue."
  },
  {
    id: "nsa203-doc27",
    title: "Gorbachev conversation with Chernyaev about Reykjavik",
    date: "1986-11-17",
    phase: "Aftermath",
    side: "Soviet",
    priority: "Core",
    type: "conversation note",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 27",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document27.pdf",
    summary: "Gorbachev tells Chernyaev that the Soviet side cannot go below Reykjavik."
  },
  {
    id: "nsa203-doc28",
    title: "Gorbachev conference with Politburo members and Central Committee secretaries",
    date: "1986-12-01",
    phase: "Aftermath",
    side: "Soviet",
    priority: "Context",
    type: "leadership conference",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 28",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document28.pdf",
    summary: "Gorbachev criticizes U.S. abandonment of SALT II and ties it to the eroding spirit of Reykjavik."
  },
  {
    id: "nsa203-doc29",
    title: "Meeting with the Joint Chiefs of Staff on NSDD 250",
    date: "1986-12-18",
    phase: "Aftermath",
    side: "US",
    priority: "Context",
    type: "staff package",
    repository: "National Security Archive",
    collection: "Reykjavik File, Document 29",
    url: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB203/Document29.pdf",
    summary: "Staff materials showing military resistance and budget concerns after the Reykjavik proposals moved into Washington follow-up."
  },
  {
    id: "nsa-road",
    title: "Gorbachev's nuclear initiative and the road to Reykjavik",
    date: "2016-10-12",
    phase: "Collections",
    side: "Bilateral",
    priority: "Context",
    type: "document collection",
    repository: "National Security Archive",
    collection: "Briefing Book No. 563",
    url: "https://nsarchive.gwu.edu/briefing-book/nuclear-vault-russia-programs/2016-10-12/gorbachevs-nuclear-initiative-january-1986",
    summary: "Thirty-two-document collection tying the January 1986 abolition initiative, U.S. internal debate, and the summit transcripts together."
  },
  {
    id: "cia-19861002",
    title: "Gorbachev's position on the eve of the summit",
    date: "1986-10-02",
    phase: "Road",
    side: "US",
    priority: "Context",
    type: "intelligence assessment",
    repository: "Reagan Library",
    collection: "Digital Library / intelligence assessment",
    url: "https://www.reaganlibrary.gov/public/digitallibrary/smof/nsc-europeanandsovietaffairs/europeanandsovietaffairs-records/r12/40-170-7451593-R12-057-2018.pdf",
    summary: "Four-page U.S. intelligence assessment of Gorbachev's domestic strength, negotiating latitude, and likely objectives before Iceland."
  },
  {
    id: "reagan-radio-1004",
    title: "Reagan radio address on the upcoming Reykjavik meeting",
    date: "1986-10-04",
    phase: "Public",
    side: "US",
    priority: "Core",
    type: "public address",
    repository: "Reagan Library",
    collection: "Public Papers",
    url: "https://www.reaganlibrary.gov/archives/speech/radio-address-nation-meeting-soviet-general-secretary-gorbachev-reykjavik-iceland",
    summary: "Reagan's pre-summit appeal to the American public and Congress before departing for Iceland."
  },
  {
    id: "reagan-keflavik-1012",
    title: "Reagan remarks to U.S. military personnel at Keflavik",
    date: "1986-10-12",
    phase: "Public",
    side: "US",
    priority: "Core",
    type: "public remarks",
    repository: "Reagan Library",
    collection: "Public Papers",
    url: "https://www.reaganlibrary.gov/research/speeches/101286a",
    summary: "First public Reagan account immediately after the hard final day in Iceland."
  },
  {
    id: "reagan-address-1013",
    title: "Reagan address to the nation on the Iceland meetings",
    date: "1986-10-13",
    phase: "Public",
    side: "US",
    priority: "Core",
    type: "televised address",
    repository: "Reagan Library",
    collection: "Public Papers",
    url: "https://www.reaganlibrary.gov/archives/speech/address-nation-meetings-soviet-general-secretary-gorbachev-iceland",
    summary: "Oval Office address framing the failed summit as a historic proposal to eliminate ballistic missiles and move toward a safer world."
  },
  {
    id: "reagan-papers-oct1986",
    title: "Public Papers of Ronald Reagan, October 1986 index",
    date: "1986-10-01",
    phase: "Public",
    side: "US",
    priority: "Lead",
    type: "index",
    repository: "Reagan Library",
    collection: "Public Papers",
    url: "https://www.reaganlibrary.gov/october-1986",
    summary: "Index to the cluster of Reykjavik statements, speeches, Q&A sessions, and press secretary statements in October 1986."
  },
  {
    id: "un-cd649",
    title: "Gorbachev statement proposing nuclear abolition by 2000",
    date: "1986-01-15",
    phase: "Road",
    side: "Soviet",
    priority: "Core",
    type: "public statement",
    repository: "United Nations Digital Library",
    collection: "CD/649",
    url: "https://digitallibrary.un.org/record/117134",
    summary: "UN-circulated statement of the January 1986 Soviet nuclear abolition initiative that framed the road to Reykjavik."
  },
  {
    id: "un-a41709",
    title: "Gorbachev press conference in Reykjavik",
    date: "1986-10-12",
    phase: "Public",
    side: "Soviet",
    priority: "Core",
    type: "press conference",
    repository: "United Nations Digital Library",
    collection: "A/41/709, S/18401",
    url: "https://digitallibrary.un.org/record/122030",
    summary: "Official UN circulation of Gorbachev's October 12 Reykjavik press conference."
  },
  {
    id: "un-a41714",
    title: "Gorbachev speech on Soviet television after Reykjavik",
    date: "1986-10-14",
    phase: "Public",
    side: "Soviet",
    priority: "Core",
    type: "televised speech",
    repository: "United Nations Digital Library",
    collection: "A/41/714, S/18403",
    url: "https://digitallibrary.un.org/record/127564",
    summary: "Official UN circulation of Gorbachev's October 14 Soviet television address on how Moscow interpreted the summit."
  },
  {
    id: "reagan-topic-guide",
    title: "Reagan Library Topic Guide: Reykjavik Summit, October 1986",
    date: "2022-12-21",
    phase: "Finding Aids",
    side: "US",
    priority: "Lead",
    type: "finding aid",
    repository: "Reagan Library",
    collection: "Topic guide",
    url: "https://www.reaganlibrary.gov/public/archives/textual/topics/reykjavik.pdf",
    summary: "Folder and case-file map for Reagan Library holdings related to Reykjavik, including WHORM and White House staff collections."
  },
  {
    id: "reagan-whorm-foreign-affairs",
    title: "WHORM Foreign Affairs description for Gorbachev/Reykjavik files",
    date: "1986-10-11",
    phase: "Finding Aids",
    side: "US",
    priority: "Lead",
    type: "finding aid",
    repository: "Reagan Library",
    collection: "WHORM Foreign Affairs",
    url: "https://www.reaganlibrary.gov/archives/subject/whorm-foreign-affairs",
    summary: "Archive description for FO006-11 and related Gorbachev/USSR summit file categories."
  },
  {
    id: "reagan-foundation-video",
    title: "Reagan Foundation video: Reykjavik Summit with Gorbachev",
    date: "1986-10-11",
    phase: "Media",
    side: "US",
    priority: "Lead",
    type: "video",
    repository: "Reagan Foundation",
    collection: "Media archive",
    url: "https://www.reaganfoundation.org/media/videos/president-reagan-s-reykjavik-summit-with-mikhail-gorbachev-on-october-11-1986",
    summary: "Archival video page for Reagan's Reykjavik summit footage."
  },
  {
    id: "commons-reykjavik",
    title: "Wikimedia Commons category: 1986 Reykjavik summit media",
    date: "1986-10-11",
    phase: "Media",
    side: "Bilateral",
    priority: "Lead",
    type: "media collection",
    repository: "Wikimedia Commons",
    collection: "1986 Reykjavik summit",
    url: "https://commons.wikimedia.org/wiki/Category:1986_Reykjav%C3%ADk_summit",
    summary: "Photographs and video files, many sourced to NARA, DPLA, and Reagan Library records."
  },
  {
    id: "thatcher-143887",
    title: "UK Embassy Reykjavik telegram to FCO on Reagan-Gorbachev meeting",
    date: "1986-10-12",
    phase: "Aftermath",
    side: "Allied",
    priority: "Context",
    type: "telegram",
    repository: "Margaret Thatcher Foundation",
    collection: "TNA PREM19/1759",
    url: "https://archive.margaretthatcher.org/doc06/861012%202330%20UKE%20Reykjavik%20to%20FCO%20GORB%20PRESS%20CONF%20PREM19-1759%20tna%20f131.pdf",
    summary: "British Embassy telegram reporting immediate reactions after Gorbachev said a historic opportunity had been missed."
  },
  {
    id: "thatcher-143836",
    title: "No. 10 record of Reagan-Thatcher phone call on Reykjavik",
    date: "1986-10-13",
    phase: "Aftermath",
    side: "Allied",
    priority: "Core",
    type: "record of conversation",
    repository: "Margaret Thatcher Foundation",
    collection: "TNA PREM19/1759",
    url: "https://archive.margaretthatcher.org/doc06/861013%20CDP%20mnt%20RR-MT%20TELCON%20PREM19-1759%20tna%20f111.pdf",
    summary: "British record of Reagan briefing Thatcher by phone after Reykjavik, important for the nuclear abolition versus ballistic missile question."
  },
  {
    id: "thatcher-143809",
    title: "White House record of Reagan-Thatcher conversation on Reykjavik",
    date: "1986-10-13",
    phase: "Aftermath",
    side: "Allied",
    priority: "Core",
    type: "record of conversation",
    repository: "Margaret Thatcher Foundation",
    collection: "Reagan Library copy",
    url: "https://archive.margaretthatcher.org/doc06/861013%20RR-MT%20telcon%20%28Sommers%20files%29.pdf",
    summary: "U.S. record of the same Reagan-Thatcher post-summit call, useful for comparison with the British version."
  },
  {
    id: "thatcher-144011",
    title: "FCO minute to No. 10 with draft congratulatory message to Reagan",
    date: "1986-10-13",
    phase: "Aftermath",
    side: "Allied",
    priority: "Context",
    type: "minute",
    repository: "Margaret Thatcher Foundation",
    collection: "TNA PREM19/1759",
    url: "https://archive.margaretthatcher.org/doc06/861013%20FCO%20to%20No.10%20BFG%20PREM19-1759%20tna%20f106.pdf",
    summary: "British draft response congratulating Reagan on getting close to a new range of agreements."
  },
  {
    id: "thatcher-144012",
    title: "FCO minute to No. 10 with draft message designed to deny Gorbachev propaganda points",
    date: "1986-10-13",
    phase: "Aftermath",
    side: "Allied",
    priority: "Context",
    type: "minute",
    repository: "Margaret Thatcher Foundation",
    collection: "TNA PREM19/1759",
    url: "https://archive.margaretthatcher.org/doc06/861013%20FCO%20to%20No.10%20TKG%20PTS%20OVERTAKEN%20PREM19-1759%20tna%20f116.pdf",
    summary: "British advice on how Thatcher should frame support for Reagan while countering Soviet post-summit messaging."
  },
  {
    id: "thatcher-143794",
    title: "Poindexter memo: Why we cannot commit to eliminating all nuclear weapons within ten years",
    date: "1986-10-17",
    phase: "Aftermath",
    side: "US",
    priority: "Core",
    type: "memorandum",
    repository: "Margaret Thatcher Foundation",
    collection: "Reagan Library copy",
    url: "https://archive.margaretthatcher.org/doc06/861017%20Poindexter%20for%20Reagan%20TEN%20YEAR%20ELIMN%20Keel%20Files.pdf",
    summary: "Key post-Reykjavik memo narrowing the U.S. follow-up from all nuclear weapons toward ballistic nuclear missiles."
  },
  {
    id: "thatcher-143977",
    title: "UK Moscow telegram: Reykjavik INF/SDI linkage",
    date: "1986-10-16",
    phase: "Aftermath",
    side: "Allied",
    priority: "Context",
    type: "telegram",
    repository: "Margaret Thatcher Foundation",
    collection: "TNA PREM19/1759",
    url: "https://archive.margaretthatcher.org/doc06/861016%200900%20UKE%20Moscow%20to%20FCO%20KARPOV%20PREM19-1759%20tna%20f32.pdf",
    summary: "British diplomatic reporting from Moscow on the Soviet position after Reykjavik."
  },
  {
    id: "last-superpower-summits",
    title: "The Last Superpower Summits source edition",
    date: "2016-11-01",
    phase: "Collections",
    side: "Bilateral",
    priority: "Lead",
    type: "published source edition",
    repository: "CEU Press / National Security Archive",
    collection: "National Security Archive Cold War Reader",
    url: "https://www.aup.nl/en/book/9789633861714/the-last-superpower-summits",
    summary: "Published primary-source edition with U.S. and Soviet transcripts and headnotes; useful for session cross-references cited by FRUS."
  }
];
